// Automatically curated fan & DJ reviews from SoundCloud
const communityReviews = [
    {
        "id": 1,
        "author": "Manuel Varella",
        "username": "Manuel Varella Dj",
        "avatar": "https://i1.sndcdn.com/avatars-TUkeLAOeMS0bhLBl-yMoxxg-large.jpg",
        "comment": "That kick hits HARD! 💣keep on moving",
        "trackTitle": "Pure Pulse (PjD | Madness Remake)",
        "trackUrl": "https://soundcloud.com/theprojectdee/purepulse",
        "trackThumb": "https://i1.sndcdn.com/artworks-tAP1ujy4i4tFQwvS-TNnCmA-t500x500.jpg",
        "date": "2026-10-09"
    },
    {
        "id": 2,
        "author": "AKA Mudlark ^",
        "username": "AKA Mudlark ^",
        "avatar": "https://i1.sndcdn.com/avatars-EMS2dg42vlOz2TVU-dSC55A-large.jpg",
        "comment": "dope 😎",
        "trackTitle": "Vertigine",
        "trackUrl": "https://soundcloud.com/theprojectdee/vertigine2035",
        "trackThumb": "https://i1.sndcdn.com/artworks-WIbJNQOCdvsv61Xz-Y8MELg-t500x500.jpg",
        "date": "2026-10-09"
    },
    {
        "id": 3,
        "author": "Harmonia At Night",
        "username": "Harmonia At Night",
        "avatar": "https://i1.sndcdn.com/avatars-000140583453-338nvj-large.jpg",
        "comment": "wild track",
        "trackTitle": "Zodiac (September Bonus Track)",
        "trackUrl": "https://soundcloud.com/theprojectdee/zodiac-september-bonus-track",
        "trackThumb": "https://i1.sndcdn.com/artworks-pzSsE3bAlqOAYT6w-GzWxQA-t500x500.jpg",
        "date": "2026-10-07"
    },
    {
        "id": 4,
        "author": "Tannova",
        "username": "Tannova",
        "avatar": "https://i1.sndcdn.com/avatars-FqOzJjgVNRqQF7s0-zOLqOA-large.jpg",
        "comment": "nice work man great tune wow love it",
        "trackTitle": "Silentium | Lux Obscura (PjD)",
        "trackUrl": "https://soundcloud.com/theprojectdee/luxobscura",
        "trackThumb": "https://i1.sndcdn.com/artworks-D4c3OlZM34IWQzLZ-ga8O9w-t500x500.jpg",
        "date": "2026-10-01"
    },
    {
        "id": 5,
        "author": "esk4pe",
        "username": "esk4pe",
        "avatar": "https://i1.sndcdn.com/avatars-DbyN39aY0zF6rrLW-7TVLCg-large.jpg",
        "comment": "I really enjoyed how the tension builds into the intense drop. The vocals sound like 2 deities recording catastrophe for posterity, lamenting, but unable to help. Really unique!",
        "trackTitle": "Japan Sinks | Sakyo Komatsu Tribute (Project Dee)",
        "trackUrl": "https://soundcloud.com/theprojectdee/jpsinks",
        "trackThumb": "https://i1.sndcdn.com/artworks-I76i4Ns0IHCncS82-WrwNcQ-t500x500.jpg",
        "date": "2026-09-30"
    },
    {
        "id": 6,
        "author": "Khaos Creator",
        "username": "Khaos Creator",
        "avatar": "https://i1.sndcdn.com/avatars-QYriw83UO1MyzVFI-ECYPyQ-large.jpg",
        "comment": "Nice mix 🤘",
        "trackTitle": "Cats - Project Dee (Original Mix)",
        "trackUrl": "https://soundcloud.com/theprojectdee/cats",
        "trackThumb": "https://i1.sndcdn.com/artworks-UYe3tOWaT3u8nSoV-7Bx6pw-t500x500.jpg",
        "date": "2026-09-03"
    },
    {
        "id": 7,
        "author": "Yavesprimo",
        "username": "Yavesprimo",
        "avatar": "https://i1.sndcdn.com/avatars-VyFRXcN45wBz4m21-7dcq9g-large.jpg",
        "comment": "sexy",
        "trackTitle": "Threshold",
        "trackUrl": "https://soundcloud.com/theprojectdee/threshold",
        "trackThumb": "https://i1.sndcdn.com/artworks-UY8bg5P5oMoPJQlq-sWVghg-t500x500.jpg",
        "date": "2026-09-30"
    },
    {
        "id": 8,
        "author": "Angel Pendragon",
        "username": "AdonaiAm ☀️",
        "avatar": "https://i1.sndcdn.com/avatars-83S5y8PjqHwrSjRi-nLdn8Q-large.jpg",
        "comment": "Gorgeous track! Very well done. ✨",
        "trackTitle": "Before The Floor Shakes",
        "trackUrl": "https://soundcloud.com/theprojectdee/before-the-floor-shakes",
        "trackThumb": "https://i1.sndcdn.com/artworks-hErGcruPbU3e4bxK-XvIkJQ-t500x500.jpg",
        "date": "2026-09-01"
    },
    {
        "id": 9,
        "author": "Make love, not war",
        "username": "Caedmon Rigby",
        "avatar": "https://i1.sndcdn.com/avatars-66P0PuI0CwgPLqIT-J319OA-large.jpg",
        "comment": "Fire tune ⚡",
        "trackTitle": "Catch the Sun",
        "trackUrl": "https://soundcloud.com/theprojectdee/thesun",
        "trackThumb": "https://i1.sndcdn.com/artworks-T4MY6Xr5Ooc77Srq-I9aMJQ-t500x500.jpg",
        "date": "2026-08-02"
    },
    {
        "id": 10,
        "author": "DKTG",
        "username": "DKTG",
        "avatar": "https://i1.sndcdn.com/avatars-yeRa60qozSyiXkqQ-yhmVZg-large.jpg",
        "comment": "Really good!",
        "trackTitle": "Come To Dubai (Original Mix)",
        "trackUrl": "https://soundcloud.com/theprojectdee/dubai",
        "trackThumb": "https://i1.sndcdn.com/artworks-hQHDnrAYWlKiuOql-KQ2Xqw-t500x500.jpg",
        "date": "2026-08-20"
    },
    {
        "id": 11,
        "author": "Harmonia At Night",
        "username": "Harmonia At Night",
        "avatar": "https://i1.sndcdn.com/avatars-000140583453-338nvj-large.jpg",
        "comment": "Epic 🔊",
        "trackTitle": "Honey and the Tide",
        "trackUrl": "https://soundcloud.com/theprojectdee/honeymoon",
        "trackThumb": "https://i1.sndcdn.com/artworks-DSMHn1DxZFl0fYr2-0UoDqQ-t500x500.png",
        "date": "2026-08-21"
    },
    {
        "id": 12,
        "author": "Jungle - Drum and Bass",
        "username": "Rokschoon",
        "avatar": "https://i1.sndcdn.com/avatars-pHOENGdsrBZfCiPm-gGXLXA-large.jpg",
        "comment": "straight art 😎",
        "trackTitle": "Angel of Light",
        "trackUrl": "https://soundcloud.com/theprojectdee/angeloflight",
        "trackThumb": "https://i1.sndcdn.com/artworks-YMPvhNSJyez7cSuY-yS96oA-t500x500.jpg",
        "date": "2026-07-23"
    },
    {
        "id": 13,
        "author": "ROSSCO",
        "username": "ROSSCO",
        "avatar": "https://i1.sndcdn.com/avatars-wxo4L3Yyx88d1ldh-QfCNnQ-large.jpg",
        "comment": "clean mix 🚀",
        "trackTitle": "The Weight of Light",
        "trackUrl": "https://soundcloud.com/theprojectdee/weightoflight",
        "trackThumb": "https://i1.sndcdn.com/artworks-bGWUf9xMzZ0ZAyjb-IM7ncw-t500x500.png",
        "date": "2026-08-03"
    },
    {
        "id": 14,
        "author": "Luovodifaberge",
        "username": "Luovodifaberge",
        "avatar": "https://i1.sndcdn.com/avatars-zyhlae8iPBwhabcu-63uPbw-large.jpg",
        "comment": "sounds good",
        "trackTitle": "The Flow of Time",
        "trackUrl": "https://soundcloud.com/theprojectdee/theflow",
        "trackThumb": "https://i1.sndcdn.com/artworks-YpySSkPUAzrphpm2-D4EA7g-t500x500.png",
        "date": "2026-08-03"
    },
    {
        "id": 15,
        "author": "Twistedreload",
        "username": "Twistedreload",
        "avatar": "https://i1.sndcdn.com/avatars-NNmSQlbcs71RyWyK-bltFag-large.jpg",
        "comment": "tidy",
        "trackTitle": "The Pressure",
        "trackUrl": "https://soundcloud.com/theprojectdee/pressure",
        "trackThumb": "https://i1.sndcdn.com/artworks-wnczJAsT5ItcEj6x-BQ8tOQ-t500x500.png",
        "date": "2026-08-04"
    },
    {
        "id": 16,
        "author": "Cloud Stalkin",
        "username": "Cloud Stalkin",
        "avatar": "https://i1.sndcdn.com/avatars-cyybf9JOwpXE8eCK-TRgqMA-large.jpg",
        "comment": "daaaaaaaam did you rub some funk in your coffee, love this",
        "trackTitle": "The Machine's Pulse",
        "trackUrl": "https://soundcloud.com/theprojectdee/machinepulse",
        "trackThumb": "https://i1.sndcdn.com/artworks-iNEGYSTXBHfAmAdL-cOf3WA-t500x500.jpg",
        "date": "2026-07-29"
    },
    {
        "id": 17,
        "author": "Mariilyz",
        "username": "Mariilyz",
        "avatar": "https://i1.sndcdn.com/avatars-PHzRuujXFTjfFOnw-zTgKVg-large.jpg",
        "comment": "more pls 💥",
        "trackTitle": "Do you remember Sài Gòn?",
        "trackUrl": "https://soundcloud.com/theprojectdee/doyouremember",
        "trackThumb": "https://i1.sndcdn.com/artworks-7H0WLy2pMYcqIP3X-WdSBDQ-t500x500.jpg",
        "date": "2026-08-07"
    },
    {
        "id": 18,
        "author": "Alex_studio",
        "username": "Alex_studio",
        "avatar": "https://i1.sndcdn.com/avatars-izdqpXY3t6TirGdm-HLY9Pw-large.jpg",
        "comment": "nice sound",
        "trackTitle": "The space in between (EssentialMix)",
        "trackUrl": "https://soundcloud.com/theprojectdee/thespacessential",
        "trackThumb": "https://i1.sndcdn.com/artworks-M7Zbe5oPWFuCUzzz-lYoAVA-t500x500.png",
        "date": "2026-02-19"
    },
    {
        "id": 19,
        "author": "Nota.Cvlt",
        "username": "Nota.Cvlt",
        "avatar": "https://i1.sndcdn.com/avatars-HGwkKQRE4x4UTuys-5TMNPA-large.jpg",
        "comment": "This is such a good song. Caught me off guard how hard it goes",
        "trackTitle": "Pure Pulse (PjD | Madness Remake)",
        "trackUrl": "https://soundcloud.com/theprojectdee/purepulse",
        "trackThumb": "https://i1.sndcdn.com/artworks-tAP1ujy4i4tFQwvS-TNnCmA-t500x500.jpg",
        "date": "2026-10-09"
    },
    {
        "id": 20,
        "author": "Paul Barrett",
        "username": "PLrM",
        "avatar": "https://i1.sndcdn.com/avatars-JXZ1DXwMozQr1SdR-jyjyUw-large.jpg",
        "comment": "This sounds massive. Great job.",
        "trackTitle": "Vertigine",
        "trackUrl": "https://soundcloud.com/theprojectdee/vertigine2035",
        "trackThumb": "https://i1.sndcdn.com/artworks-WIbJNQOCdvsv61Xz-Y8MELg-t500x500.jpg",
        "date": "2026-10-09"
    },
    {
        "id": 21,
        "author": "KRT Production",
        "username": "KRT Production",
        "avatar": "https://i1.sndcdn.com/avatars-SXbacvZ3UrAOoI1K-QHyyFQ-large.jpg",
        "comment": "perfection 💥",
        "trackTitle": "Zodiac (September Bonus Track)",
        "trackUrl": "https://soundcloud.com/theprojectdee/zodiac-september-bonus-track",
        "trackThumb": "https://i1.sndcdn.com/artworks-pzSsE3bAlqOAYT6w-GzWxQA-t500x500.jpg",
        "date": "2026-10-06"
    },
    {
        "id": 22,
        "author": "R I C H B I T O M U S I C",
        "username": "M U S I C",
        "avatar": "https://i1.sndcdn.com/avatars-vGNLc4A6rr6DiKuO-vSujiw-large.jpg",
        "comment": "Superb",
        "trackTitle": "Silentium | Lux Obscura (PjD)",
        "trackUrl": "https://soundcloud.com/theprojectdee/luxobscura",
        "trackThumb": "https://i1.sndcdn.com/artworks-D4c3OlZM34IWQzLZ-ga8O9w-t500x500.jpg",
        "date": "2026-09-29"
    },
    {
        "id": 23,
        "author": "AKA OlynCTrance",
        "username": "Olyn.cs",
        "avatar": "https://i1.sndcdn.com/avatars-Jdh6IbperzqPqfom-K4mzbg-large.jpg",
        "comment": "Buen tema de electronica. los drums muy crigientes",
        "trackTitle": "Japan Sinks | Sakyo Komatsu Tribute (Project Dee)",
        "trackUrl": "https://soundcloud.com/theprojectdee/jpsinks",
        "trackThumb": "https://i1.sndcdn.com/artworks-I76i4Ns0IHCncS82-WrwNcQ-t500x500.jpg",
        "date": "2026-09-21"
    },
    {
        "id": 24,
        "author": "Robert Flynn",
        "username": "Robert Flynn",
        "avatar": "https://i1.sndcdn.com/avatars-bC041rEHE7JhnGsK-monzgA-large.jpg",
        "comment": "Tell me NO AI....TELL ME",
        "trackTitle": "Cats - Project Dee (Original Mix)",
        "trackUrl": "https://soundcloud.com/theprojectdee/cats",
        "trackThumb": "https://i1.sndcdn.com/artworks-UYe3tOWaT3u8nSoV-7Bx6pw-t500x500.jpg",
        "date": "2026-09-02"
    },
    {
        "id": 25,
        "author": "Khaos Creator",
        "username": "Khaos Creator",
        "avatar": "https://i1.sndcdn.com/avatars-QYriw83UO1MyzVFI-ECYPyQ-large.jpg",
        "comment": "smooth af 🙌",
        "trackTitle": "Threshold",
        "trackUrl": "https://soundcloud.com/theprojectdee/threshold",
        "trackThumb": "https://i1.sndcdn.com/artworks-UY8bg5P5oMoPJQlq-sWVghg-t500x500.jpg",
        "date": "2026-09-21"
    },
    {
        "id": 26,
        "author": "Wilson Gomes",
        "username": "Wilson Gomes",
        "avatar": "https://i1.sndcdn.com/avatars-DBK1Z9GKW26aOVlW-OzXLog-large.jpg",
        "comment": "I love this craze beats, shaking us inside!",
        "trackTitle": "Before The Floor Shakes",
        "trackUrl": "https://soundcloud.com/theprojectdee/before-the-floor-shakes",
        "trackThumb": "https://i1.sndcdn.com/artworks-hErGcruPbU3e4bxK-XvIkJQ-t500x500.jpg",
        "date": "2026-08-31"
    },
    {
        "id": 27,
        "author": "Zawley",
        "username": "Zawley",
        "avatar": "https://i1.sndcdn.com/avatars-xpQM6UizvtqEGJ0J-Uj0Yug-large.jpg",
        "comment": "Got me fishing pumping over here",
        "trackTitle": "Catch the Sun",
        "trackUrl": "https://soundcloud.com/theprojectdee/thesun",
        "trackThumb": "https://i1.sndcdn.com/artworks-T4MY6Xr5Ooc77Srq-I9aMJQ-t500x500.jpg",
        "date": "2026-08-02"
    },
    {
        "id": 28,
        "author": "Yasin Borry",
        "username": "BYAS",
        "avatar": "https://i1.sndcdn.com/avatars-BzpeLbRvfBK33R9Q-QcpK4w-large.jpg",
        "comment": "Really dope groove and nice male voice sync",
        "trackTitle": "Come To Dubai (Original Mix)",
        "trackUrl": "https://soundcloud.com/theprojectdee/dubai",
        "trackThumb": "https://i1.sndcdn.com/artworks-hQHDnrAYWlKiuOql-KQ2Xqw-t500x500.jpg",
        "date": "2026-08-20"
    },
    {
        "id": 29,
        "author": "Marcio Reis",
        "username": "Reeis",
        "avatar": "https://i1.sndcdn.com/avatars-mESAMtnB20DGKhO3-B4VEvw-large.jpg",
        "comment": "Bom trabalho feito aqui ! Track interessante boa produção",
        "trackTitle": "Honey and the Tide",
        "trackUrl": "https://soundcloud.com/theprojectdee/honeymoon",
        "trackThumb": "https://i1.sndcdn.com/artworks-DSMHn1DxZFl0fYr2-0UoDqQ-t500x500.png",
        "date": "2026-08-21"
    },
    {
        "id": 30,
        "author": "Zawley",
        "username": "Zawley",
        "avatar": "https://i1.sndcdn.com/avatars-xpQM6UizvtqEGJ0J-Uj0Yug-large.jpg",
        "comment": "This song is making me flow through time just right",
        "trackTitle": "The Flow of Time",
        "trackUrl": "https://soundcloud.com/theprojectdee/theflow",
        "trackThumb": "https://i1.sndcdn.com/artworks-YpySSkPUAzrphpm2-D4EA7g-t500x500.png",
        "date": "2026-08-03"
    },
    {
        "id": 31,
        "author": "Gerhard Manthau",
        "username": "Mexicomaus - Label:Psychedelic new  Style  Records",
        "avatar": "https://i1.sndcdn.com/avatars-BvxReMtOeW0ywW6I-tK7RfQ-large.jpg",
        "comment": "mega sseion",
        "trackTitle": "The Pressure",
        "trackUrl": "https://soundcloud.com/theprojectdee/pressure",
        "trackThumb": "https://i1.sndcdn.com/artworks-wnczJAsT5ItcEj6x-BQ8tOQ-t500x500.png",
        "date": "2026-07-31"
    },
    {
        "id": 32,
        "author": "Jonas Bergström",
        "username": "GeezyorK",
        "avatar": "https://i1.sndcdn.com/avatars-hiI74ZKD2pRoNRQL-eU1CnA-large.jpg",
        "comment": "Great funky vibes here. Great sounding track",
        "trackTitle": "The Machine's Pulse",
        "trackUrl": "https://soundcloud.com/theprojectdee/machinepulse",
        "trackThumb": "https://i1.sndcdn.com/artworks-iNEGYSTXBHfAmAdL-cOf3WA-t500x500.jpg",
        "date": "2026-07-29"
    },
    {
        "id": 33,
        "author": "Alvaro Castrillón",
        "username": "Alvaro Castrillon Music",
        "avatar": "https://i1.sndcdn.com/avatars-JLfbrmHLgpDurYia-7zlnTQ-large.jpg",
        "comment": "respect 💎",
        "trackTitle": "Do you remember Sài Gòn?",
        "trackUrl": "https://soundcloud.com/theprojectdee/doyouremember",
        "trackThumb": "https://i1.sndcdn.com/artworks-7H0WLy2pMYcqIP3X-WdSBDQ-t500x500.jpg",
        "date": "2026-08-07"
    },
    {
        "id": 34,
        "author": "Vorales",
        "username": "VORALES",
        "avatar": "https://i1.sndcdn.com/avatars-FYW6lXbRmiMWiMEI-r8vYPg-large.jpg",
        "comment": "melodia incrivel dessa sonoridade bro",
        "trackTitle": "Pure Pulse (PjD | Madness Remake)",
        "trackUrl": "https://soundcloud.com/theprojectdee/purepulse",
        "trackThumb": "https://i1.sndcdn.com/artworks-tAP1ujy4i4tFQwvS-TNnCmA-t500x500.jpg",
        "date": "2026-10-09"
    },
    {
        "id": 35,
        "author": "Manuel Marino",
        "username": "Manuel Marino",
        "avatar": "https://i1.sndcdn.com/avatars-Ez2Ut6Y4HpEfAhHn-HjlxBA-large.jpg",
        "comment": "It's really beautiful, it sounds like a sci-fi soundtrack.",
        "trackTitle": "Vertigine",
        "trackUrl": "https://soundcloud.com/theprojectdee/vertigine2035",
        "trackThumb": "https://i1.sndcdn.com/artworks-WIbJNQOCdvsv61Xz-Y8MELg-t500x500.jpg",
        "date": "2026-10-04"
    },
    {
        "id": 36,
        "author": "Resazat Ay",
        "username": "Resazat",
        "avatar": "https://i1.sndcdn.com/avatars-fiJ6W3WXEqL2jPsO-ucYcCA-large.jpg",
        "comment": "this knocks",
        "trackTitle": "Zodiac (September Bonus Track)",
        "trackUrl": "https://soundcloud.com/theprojectdee/zodiac-september-bonus-track",
        "trackThumb": "https://i1.sndcdn.com/artworks-pzSsE3bAlqOAYT6w-GzWxQA-t500x500.jpg",
        "date": "2026-10-06"
    },
    {
        "id": 37,
        "author": "Rbh1",
        "username": "HXsoundZ™",
        "avatar": "https://i1.sndcdn.com/avatars-SqxHa9oVvM2qjgWu-TuOGyA-large.jpg",
        "comment": "Heat 😎",
        "trackTitle": "Silentium | Lux Obscura (PjD)",
        "trackUrl": "https://soundcloud.com/theprojectdee/luxobscura",
        "trackThumb": "https://i1.sndcdn.com/artworks-D4c3OlZM34IWQzLZ-ga8O9w-t500x500.jpg",
        "date": "2026-09-28"
    },
    {
        "id": 38,
        "author": "Zingoes Zaur",
        "username": "Zingosaur",
        "avatar": "https://i1.sndcdn.com/avatars-Y5eEi6WyFthRyEPV-fBouMA-large.jpg",
        "comment": "uplifting",
        "trackTitle": "Japan Sinks | Sakyo Komatsu Tribute (Project Dee)",
        "trackUrl": "https://soundcloud.com/theprojectdee/jpsinks",
        "trackThumb": "https://i1.sndcdn.com/artworks-I76i4Ns0IHCncS82-WrwNcQ-t500x500.jpg",
        "date": "2026-09-19"
    },
    {
        "id": 39,
        "author": "I AM®",
        "username": "I AM®",
        "avatar": "https://i1.sndcdn.com/avatars-zNzdyArqeozIe0aU-R9pZxg-large.jpg",
        "comment": "Wow you sure can capture the moment",
        "trackTitle": "Cats - Project Dee (Original Mix)",
        "trackUrl": "https://soundcloud.com/theprojectdee/cats",
        "trackThumb": "https://i1.sndcdn.com/artworks-UYe3tOWaT3u8nSoV-7Bx6pw-t500x500.jpg",
        "date": "2026-08-31"
    },
    {
        "id": 40,
        "author": "Hagar Shay",
        "username": "Hagar Shay",
        "avatar": "https://i1.sndcdn.com/avatars-3E18YZepkqYz2Nf2-FU9XLw-large.jpg",
        "comment": "The baseline gives this great momentum",
        "trackTitle": "Threshold",
        "trackUrl": "https://soundcloud.com/theprojectdee/threshold",
        "trackThumb": "https://i1.sndcdn.com/artworks-UY8bg5P5oMoPJQlq-sWVghg-t500x500.jpg",
        "date": "2026-09-18"
    },
    {
        "id": 41,
        "author": "TINT",
        "username": "TINT",
        "avatar": "https://i1.sndcdn.com/avatars-sIeLfvAFjIuQPlV4-05UwxQ-large.jpg",
        "comment": "Nice, I like the fast paced beat on this.",
        "trackTitle": "Before The Floor Shakes",
        "trackUrl": "https://soundcloud.com/theprojectdee/before-the-floor-shakes",
        "trackThumb": "https://i1.sndcdn.com/artworks-hErGcruPbU3e4bxK-XvIkJQ-t500x500.jpg",
        "date": "2026-08-28"
    },
    {
        "id": 42,
        "author": "Edmmania",
        "username": "Edmmania",
        "avatar": "https://i1.sndcdn.com/avatars-000757534276-6ixoa8-large.jpg",
        "comment": "The energy and production in this track are very groovy",
        "trackTitle": "Catch the Sun",
        "trackUrl": "https://soundcloud.com/theprojectdee/thesun",
        "trackThumb": "https://i1.sndcdn.com/artworks-T4MY6Xr5Ooc77Srq-I9aMJQ-t500x500.jpg",
        "date": "2026-07-27"
    },
    {
        "id": 43,
        "author": "SØLIX",
        "username": "SØLIX",
        "avatar": "https://i1.sndcdn.com/avatars-zznbzZQyP3bCCaOT-mHBcVw-large.jpg",
        "comment": "Great track , looking forward to putting this in my next mixtape",
        "trackTitle": "Come To Dubai (Original Mix)",
        "trackUrl": "https://soundcloud.com/theprojectdee/dubai",
        "trackThumb": "https://i1.sndcdn.com/artworks-hQHDnrAYWlKiuOql-KQ2Xqw-t500x500.jpg",
        "date": "2026-08-17"
    },
    {
        "id": 44,
        "author": "Kouture Music",
        "username": "Kouture Music",
        "avatar": "https://i1.sndcdn.com/avatars-xdUkjspI5kdSdfzg-zsIuow-large.jpg",
        "comment": "i like it man bravo coool work dudeee",
        "trackTitle": "Honey and the Tide",
        "trackUrl": "https://soundcloud.com/theprojectdee/honeymoon",
        "trackThumb": "https://i1.sndcdn.com/artworks-DSMHn1DxZFl0fYr2-0UoDqQ-t500x500.png",
        "date": "2026-08-13"
    },
    {
        "id": 45,
        "author": "ShaqiLLiWiLL AKA Black Trash T AKA The Phoeroach",
        "username": "ShaqiLLiWiLL AKA Black Trash T AKA The Phoeroach",
        "avatar": "https://i1.sndcdn.com/avatars-q8SDqb4NaBq6nThB-xxNltw-large.jpg",
        "comment": "this is cold and fire u fd up the climate",
        "trackTitle": "The Flow of Time",
        "trackUrl": "https://soundcloud.com/theprojectdee/theflow",
        "trackThumb": "https://i1.sndcdn.com/artworks-YpySSkPUAzrphpm2-D4EA7g-t500x500.png",
        "date": "2026-07-26"
    },
    {
        "id": 46,
        "author": "Borislav Đurinec",
        "username": "Van De Bork",
        "avatar": "https://i1.sndcdn.com/avatars-hCoF95LtUb3mqJQe-9gGqHg-large.jpg",
        "comment": "Wow!",
        "trackTitle": "The Pressure",
        "trackUrl": "https://soundcloud.com/theprojectdee/pressure",
        "trackThumb": "https://i1.sndcdn.com/artworks-wnczJAsT5ItcEj6x-BQ8tOQ-t500x500.png",
        "date": "2026-07-22"
    },
    {
        "id": 47,
        "author": "Mitchel Branston",
        "username": "Umshini Wena",
        "avatar": "https://i1.sndcdn.com/avatars-DMQFrirA29xRyJyz-Ms7cOg-large.jpg",
        "comment": "Deep house gold!! love the drops great work mate!",
        "trackTitle": "The Machine's Pulse",
        "trackUrl": "https://soundcloud.com/theprojectdee/machinepulse",
        "trackThumb": "https://i1.sndcdn.com/artworks-iNEGYSTXBHfAmAdL-cOf3WA-t500x500.jpg",
        "date": "2026-07-29"
    },
    {
        "id": 48,
        "author": "Kid Boozie",
        "username": "Kid Boozie",
        "avatar": "https://i1.sndcdn.com/avatars-LrRMp4WHMmRMrSWs-rYjZAA-large.jpg",
        "comment": "I could definitely see myself coming back to this one..",
        "trackTitle": "Do you remember Sài Gòn?",
        "trackUrl": "https://soundcloud.com/theprojectdee/doyouremember",
        "trackThumb": "https://i1.sndcdn.com/artworks-7H0WLy2pMYcqIP3X-WdSBDQ-t500x500.jpg",
        "date": "2026-08-07"
    },
    {
        "id": 49,
        "author": "Rbh1",
        "username": "HXsoundZ™",
        "avatar": "https://i1.sndcdn.com/avatars-SqxHa9oVvM2qjgWu-TuOGyA-large.jpg",
        "comment": "this bangs",
        "trackTitle": "Pure Pulse (PjD | Madness Remake)",
        "trackUrl": "https://soundcloud.com/theprojectdee/purepulse",
        "trackThumb": "https://i1.sndcdn.com/artworks-tAP1ujy4i4tFQwvS-TNnCmA-t500x500.jpg",
        "date": "2026-10-09"
    },
    {
        "id": 50,
        "author": "Cocoa Spoon",
        "username": "Cocoa Spoon",
        "avatar": "https://i1.sndcdn.com/avatars-000609932442-5xw988-large.jpg",
        "comment": "Awesome bro, well done on this one",
        "trackTitle": "Vertigine",
        "trackUrl": "https://soundcloud.com/theprojectdee/vertigine2035",
        "trackThumb": "https://i1.sndcdn.com/artworks-WIbJNQOCdvsv61Xz-Y8MELg-t500x500.jpg",
        "date": "2026-10-03"
    },
    {
        "id": 51,
        "author": "Robert Grigg",
        "username": "Robert Grigg",
        "avatar": "https://i1.sndcdn.com/avatars-G4zBIMLqKy7FVY1N-JrTwqA-large.jpg",
        "comment": "Nice 🤘",
        "trackTitle": "Zodiac (September Bonus Track)",
        "trackUrl": "https://soundcloud.com/theprojectdee/zodiac-september-bonus-track",
        "trackThumb": "https://i1.sndcdn.com/artworks-pzSsE3bAlqOAYT6w-GzWxQA-t500x500.jpg",
        "date": "2026-10-01"
    },
    {
        "id": 52,
        "author": "EgoVerus",
        "username": "EgoVerus",
        "avatar": "https://i1.sndcdn.com/avatars-e4XfOwUjWqyfU3rJ-2TIQrA-large.jpg",
        "comment": "An exceptionally original composition. An interesting blend of styles.",
        "trackTitle": "Silentium | Lux Obscura (PjD)",
        "trackUrl": "https://soundcloud.com/theprojectdee/luxobscura",
        "trackThumb": "https://i1.sndcdn.com/artworks-D4c3OlZM34IWQzLZ-ga8O9w-t500x500.jpg",
        "date": "2026-09-27"
    },
    {
        "id": 53,
        "author": "Jiri Boruvka",
        "username": "Juroz",
        "avatar": "https://i1.sndcdn.com/avatars-dGKCllsikU9tQqOV-xdknTA-large.jpg",
        "comment": "wild track 👏",
        "trackTitle": "Japan Sinks | Sakyo Komatsu Tribute (Project Dee)",
        "trackUrl": "https://soundcloud.com/theprojectdee/jpsinks",
        "trackThumb": "https://i1.sndcdn.com/artworks-I76i4Ns0IHCncS82-WrwNcQ-t500x500.jpg",
        "date": "2026-09-17"
    },
    {
        "id": 54,
        "author": "Iggor Lopes",
        "username": "Space Pirate",
        "avatar": "https://i1.sndcdn.com/avatars-zxabsJ2S6NbdOpX9-9S347w-large.jpg",
        "comment": "insane beat",
        "trackTitle": "Cats - Project Dee (Original Mix)",
        "trackUrl": "https://soundcloud.com/theprojectdee/cats",
        "trackThumb": "https://i1.sndcdn.com/artworks-UYe3tOWaT3u8nSoV-7Bx6pw-t500x500.jpg",
        "date": "2026-08-30"
    },
    {
        "id": 55,
        "author": "craig jones",
        "username": "Onizanka 鬼残歌",
        "avatar": "https://i1.sndcdn.com/avatars-4ZiS2TdwOj7y9Fkc-OWBdoA-large.jpg",
        "comment": "straight gold 🙌",
        "trackTitle": "Threshold",
        "trackUrl": "https://soundcloud.com/theprojectdee/threshold",
        "trackThumb": "https://i1.sndcdn.com/artworks-UY8bg5P5oMoPJQlq-sWVghg-t500x500.jpg",
        "date": "2026-09-18"
    },
    {
        "id": 56,
        "author": "Ray Hermann Angossio Liwa",
        "username": "Alpha Mystery",
        "avatar": "https://i1.sndcdn.com/avatars-mpnsWdqmAVnNUE9L-zPxFEQ-large.jpg",
        "comment": "This before the floor shakes is amazing",
        "trackTitle": "Before The Floor Shakes",
        "trackUrl": "https://soundcloud.com/theprojectdee/before-the-floor-shakes",
        "trackThumb": "https://i1.sndcdn.com/artworks-hErGcruPbU3e4bxK-XvIkJQ-t500x500.jpg",
        "date": "2026-08-28"
    },
    {
        "id": 57,
        "author": "Oscar Richardson",
        "username": "R.I.C.O",
        "avatar": "https://i1.sndcdn.com/avatars-Zz7W8vtwxebY3C5R-iPoCKA-large.jpg",
        "comment": "And the other thing I want is a little more than that",
        "trackTitle": "Catch the Sun",
        "trackUrl": "https://soundcloud.com/theprojectdee/thesun",
        "trackThumb": "https://i1.sndcdn.com/artworks-T4MY6Xr5Ooc77Srq-I9aMJQ-t500x500.jpg",
        "date": "2026-07-20"
    },
    {
        "id": 58,
        "author": "Cade Gallo",
        "username": "Cade Gallo",
        "avatar": "https://i1.sndcdn.com/avatars-DIV0xzxQxG1VHzp5-RRPmdg-large.jpg",
        "comment": "Love the track, the vibe is high, its on fire..",
        "trackTitle": "Come To Dubai (Original Mix)",
        "trackUrl": "https://soundcloud.com/theprojectdee/dubai",
        "trackThumb": "https://i1.sndcdn.com/artworks-hQHDnrAYWlKiuOql-KQ2Xqw-t500x500.jpg",
        "date": "2026-08-01"
    },
    {
        "id": 59,
        "author": "Gerhard Manthau",
        "username": "Mexicomaus - Label:Psychedelic new  Style  Records",
        "avatar": "https://i1.sndcdn.com/avatars-BvxReMtOeW0ywW6I-tK7RfQ-large.jpg",
        "comment": "tis is amagical vibration",
        "trackTitle": "Honey and the Tide",
        "trackUrl": "https://soundcloud.com/theprojectdee/honeymoon",
        "trackThumb": "https://i1.sndcdn.com/artworks-DSMHn1DxZFl0fYr2-0UoDqQ-t500x500.png",
        "date": "2026-07-31"
    },
    {
        "id": 60,
        "author": "Karl Heimgartner",
        "username": "Karl Heinz - Heimgartner",
        "avatar": "https://i1.sndcdn.com/avatars-DqQUSNTg3LCgru8M-0p4gAA-large.jpg",
        "comment": "epic energy 💎",
        "trackTitle": "The Flow of Time",
        "trackUrl": "https://soundcloud.com/theprojectdee/theflow",
        "trackThumb": "https://i1.sndcdn.com/artworks-YpySSkPUAzrphpm2-D4EA7g-t500x500.png",
        "date": "2026-07-23"
    },
    {
        "id": 61,
        "author": "SYS.GEN",
        "username": "SYS.GEN",
        "avatar": "https://i1.sndcdn.com/avatars-ox6MHFMQgCAeBDgW-ZFlfyA-large.jpg",
        "comment": "SMASHING HIT MATE, WHAT A BANGER, THE VOCALS ARE SICK",
        "trackTitle": "The Pressure",
        "trackUrl": "https://soundcloud.com/theprojectdee/pressure",
        "trackThumb": "https://i1.sndcdn.com/artworks-wnczJAsT5ItcEj6x-BQ8tOQ-t500x500.png",
        "date": "2026-07-22"
    },
    {
        "id": 62,
        "author": "Record Label",
        "username": "Quintessential Records",
        "avatar": "https://i1.sndcdn.com/avatars-TinHNlPtg5Ge4Z2H-nYh02w-large.jpg",
        "comment": "I love the way the male and female vocals compliment each other!",
        "trackTitle": "Do you remember Sài Gòn?",
        "trackUrl": "https://soundcloud.com/theprojectdee/doyouremember",
        "trackThumb": "https://i1.sndcdn.com/artworks-7H0WLy2pMYcqIP3X-WdSBDQ-t500x500.jpg",
        "date": "2026-08-07"
    }
];
